export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_ATTEMPT = 'LOGOUT_ATTEMPT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const PROFILE_SWITCHED = 'PROFILE_SWITCHED'
export const PROFILE_FETCHING = 'PROFILE_FETCHING'

export const ARTICLES_FETCHED = 'ARTICLES_FETCHED'
export const FETCHING = 'FETCHING'

export const MESSAGE_RECIVED = 'MESSAGE_RECIVED'
